[package]
name = "avian_bullet_trajectory"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
avian3d.workspace = true
bevy.workspace = true
