[alias]
make = ["bin", "cargo-make"]
nextest = ["bin", "cargo-nextest"]
remove = ["bin", "cargo-rm"]
upgrade-local = ["bin", "cargo-upgrade"]
watch = ["bin", "cargo-watch"]
dx = ["bin", "dx", "serve", "--hot-patch"]
